import type { MostConcededEntry, FastestGoalEntry } from "../lib/types";

// Generated by scripts/update-bonus-stats.ts from the openfootball/worldcup.json feed (the
// whole tournament — group stage and knockouts both, unlike matches.ts which is knockout-only).
// Do not hand-edit the GENERATED_* values below; the next scheduled run overwrites them. For a
// one-off manual correction, use BONUS_OVERRIDES instead.
//
// One-off manual pin: Morocco's Ismael Saibari and Paraguay's Matías Galarza both scored in
// minute 2 (Matchday 9, 2026-06-19) — the script itself does no tie-breaking (whichever it finds
// first just keeps the lead), so this pins the display to Paraguay per direct request. Remove
// once Paraguay is no longer the fastest-goal leader; revisit case-by-case if another tie shows up.
const BONUS_OVERRIDES: {
  mostConceded?: MostConcededEntry;
  fastestGoal?: FastestGoalEntry;
} = {
  fastestGoal: {
    teamId: "PAR",
    scorerName: "Matías Galarza",
    minute: "2",
    minuteValue: 2,
    round: "Matchday 9",
    date: "2026-06-19",
  },
};

// --- GENERATED-BEGIN ---
const GENERATED_MOST_CONCEDED: MostConcededEntry | undefined = {
  teamId: "CUW",
  goalsConceded: 7,
  opponentTeamId: "GER",
  round: "Matchday 4",
  date: "2026-06-14"
};
const GENERATED_FASTEST_GOAL: FastestGoalEntry | undefined = {
  teamId: "MAR",
  scorerName: "Ismael Saibari",
  minute: "2",
  minuteValue: 2,
  round: "Matchday 9",
  date: "2026-06-19"
};
// --- GENERATED-END ---

export const MOST_CONCEDED: MostConcededEntry | undefined =
  BONUS_OVERRIDES.mostConceded ?? GENERATED_MOST_CONCEDED;
export const FASTEST_GOAL: FastestGoalEntry | undefined =
  BONUS_OVERRIDES.fastestGoal ?? GENERATED_FASTEST_GOAL;
