import type { KnockoutMatch, KnockoutRound } from "../lib/types";

// Generated by scripts/update-bracket.ts from openfootball/worldcup.json (Round of 32
// onward — this app doesn't track individual group-stage matches). Do not hand-edit the
// GENERATED_MATCHES array below; the next scheduled run overwrites it. For one-off manual
// corrections (e.g. the feed is late or wrong), add an entry to MATCH_OVERRIDES instead.
const MATCH_OVERRIDES: Partial<Record<string, Partial<KnockoutMatch>>> = {
  // Keyed by `${round}-${slot}`, e.g. "R32-0". Example (delete once unneeded):
  // "R32-0": { winnerId: "ENG" },
};

// --- GENERATED-BEGIN ---
const GENERATED_MATCHES: KnockoutMatch[] = [
  {round:"R32",slot:0,matchNum:74,team1Id:"GER",team2Id:"PAR",score1:3,score2:4,ftScore1:1,ftScore2:1,wentToPenalties:true,winnerId:"PAR",date:"2026-06-29",venue:"Boston (Foxborough)"},
  {round:"R32",slot:1,matchNum:77,team1Id:"FRA",team2Id:"SWE",score1:3,score2:0,ftScore1:3,ftScore2:0,winnerId:"FRA",date:"2026-06-30",venue:"New York/New Jersey (East Rutherford)"},
  {round:"R32",slot:2,matchNum:73,team1Id:"RSA",team2Id:"CAN",score1:0,score2:1,ftScore1:0,ftScore2:1,winnerId:"CAN",date:"2026-06-28",venue:"Los Angeles (Inglewood)"},
  {round:"R32",slot:3,matchNum:75,team1Id:"NED",team2Id:"MAR",score1:2,score2:3,ftScore1:1,ftScore2:1,wentToPenalties:true,winnerId:"MAR",date:"2026-06-29",venue:"Monterrey (Guadalupe)"},
  {round:"R32",slot:4,matchNum:83,team1Id:"POR",team2Id:"CRO",score1:2,score2:1,ftScore1:2,ftScore2:1,winnerId:"POR",date:"2026-07-02",venue:"Toronto"},
  {round:"R32",slot:5,matchNum:84,team1Id:"ESP",team2Id:"AUT",score1:3,score2:0,ftScore1:3,ftScore2:0,winnerId:"ESP",date:"2026-07-02",venue:"Los Angeles (Inglewood)"},
  {round:"R32",slot:6,matchNum:81,team1Id:"USA",team2Id:"BIH",score1:2,score2:0,ftScore1:2,ftScore2:0,winnerId:"USA",date:"2026-07-01",venue:"San Francisco Bay Area (Santa Clara)"},
  {round:"R32",slot:7,matchNum:82,team1Id:"BEL",team2Id:"SEN",score1:3,score2:2,ftScore1:2,ftScore2:2,winnerId:"BEL",date:"2026-07-01",venue:"Seattle"},
  {round:"R32",slot:8,matchNum:76,team1Id:"BRA",team2Id:"JPN",score1:2,score2:1,ftScore1:2,ftScore2:1,winnerId:"BRA",date:"2026-06-29",venue:"Houston"},
  {round:"R32",slot:9,matchNum:78,team1Id:"CIV",team2Id:"NOR",score1:1,score2:2,ftScore1:1,ftScore2:2,winnerId:"NOR",date:"2026-06-30",venue:"Dallas (Arlington)"},
  {round:"R32",slot:10,matchNum:79,team1Id:"MEX",team2Id:"ECU",score1:2,score2:0,ftScore1:2,ftScore2:0,winnerId:"MEX",date:"2026-06-30",venue:"Mexico City"},
  {round:"R32",slot:11,matchNum:80,team1Id:"ENG",team2Id:"COD",score1:2,score2:1,ftScore1:2,ftScore2:1,winnerId:"ENG",date:"2026-07-01",venue:"Atlanta"},
  {round:"R32",slot:12,matchNum:86,team1Id:"ARG",team2Id:"CPV",date:"2026-07-03",venue:"Miami (Miami Gardens)"},
  {round:"R32",slot:13,matchNum:88,team1Id:"AUS",team2Id:"EGY",date:"2026-07-03",venue:"Dallas (Arlington)"},
  {round:"R32",slot:14,matchNum:85,team1Id:"SUI",team2Id:"ALG",score1:2,score2:0,ftScore1:2,ftScore2:0,winnerId:"SUI",date:"2026-07-02",venue:"Vancouver"},
  {round:"R32",slot:15,matchNum:87,team1Id:"COL",team2Id:"GHA",date:"2026-07-03",venue:"Kansas City"},
  {round:"R16",slot:0,matchNum:89,team1Id:"PAR",team2Id:"FRA",date:"2026-07-04",venue:"Philadelphia"},
  {round:"R16",slot:1,matchNum:90,team1Id:"CAN",team2Id:"MAR",date:"2026-07-04",venue:"Houston"},
  {round:"R16",slot:2,matchNum:93,team1Id:"POR",team2Id:"ESP",date:"2026-07-06",venue:"Dallas (Arlington)"},
  {round:"R16",slot:3,matchNum:94,team1Id:"USA",team2Id:"BEL",date:"2026-07-06",venue:"Seattle"},
  {round:"R16",slot:4,matchNum:91,team1Id:"BRA",team2Id:"NOR",date:"2026-07-05",venue:"New York/New Jersey (East Rutherford)"},
  {round:"R16",slot:5,matchNum:92,team1Id:"MEX",team2Id:"ENG",date:"2026-07-05",venue:"Mexico City"},
  {round:"R16",slot:6,matchNum:95,team1Placeholder:"W86",team2Placeholder:"W88",date:"2026-07-07",venue:"Atlanta"},
  {round:"R16",slot:7,matchNum:96,team1Id:"SUI",team2Placeholder:"W87",date:"2026-07-07",venue:"Vancouver"},
  {round:"QF",slot:0,matchNum:97,team1Placeholder:"W89",team2Placeholder:"W90",date:"2026-07-09",venue:"Boston (Foxborough)"},
  {round:"QF",slot:1,matchNum:98,team1Placeholder:"W93",team2Placeholder:"W94",date:"2026-07-10",venue:"Los Angeles (Inglewood)"},
  {round:"QF",slot:2,matchNum:99,team1Placeholder:"W91",team2Placeholder:"W92",date:"2026-07-11",venue:"Miami (Miami Gardens)"},
  {round:"QF",slot:3,matchNum:100,team1Placeholder:"W95",team2Placeholder:"W96",date:"2026-07-11",venue:"Kansas City"},
  {round:"SF",slot:0,matchNum:101,team1Placeholder:"W97",team2Placeholder:"W98",date:"2026-07-14",venue:"Dallas (Arlington)"},
  {round:"SF",slot:1,matchNum:102,team1Placeholder:"W99",team2Placeholder:"W100",date:"2026-07-15",venue:"Atlanta"},
  {round:"THIRD",slot:0,matchNum:103,team1Placeholder:"L101",team2Placeholder:"L102",date:"2026-07-18",venue:"Miami (Miami Gardens)"},
  {round:"FINAL",slot:0,matchNum:104,team1Placeholder:"W101",team2Placeholder:"W102",date:"2026-07-19",venue:"New York/New Jersey (East Rutherford)"}
];
// --- GENERATED-END ---

export const MATCHES: KnockoutMatch[] = GENERATED_MATCHES.map((m) => ({
  ...m,
  ...MATCH_OVERRIDES[`${m.round}-${m.slot}`],
}));

export const hasMatches = (): boolean => MATCHES.length > 0;

const ROUND_ORDER: KnockoutRound[] = ["R32", "R16", "QF", "SF", "THIRD", "FINAL"];

export const MATCHES_BY_ROUND: Record<KnockoutRound, KnockoutMatch[]> = {
  R32: [],
  R16: [],
  QF: [],
  SF: [],
  THIRD: [],
  FINAL: [],
};
for (const m of MATCHES) MATCHES_BY_ROUND[m.round].push(m);
for (const round of ROUND_ORDER) {
  MATCHES_BY_ROUND[round].sort((a, b) => a.slot - b.slot);
}

// A team is "out": it lost a played knockout match, or — once the Round of 32 lineup is
// fully known — it never appears in that lineup at all (eliminated in the group stage,
// which this bracket doesn't otherwise track).
const r32TeamIds = new Set<string>();
for (const m of MATCHES_BY_ROUND.R32) {
  if (m.team1Id) r32TeamIds.add(m.team1Id);
  if (m.team2Id) r32TeamIds.add(m.team2Id);
}
const groupStageComplete = r32TeamIds.size === 32;

const knockoutLosers = new Set<string>();
for (const m of MATCHES) {
  // The third-place match never changes anyone's elimination status: both participants
  // already lost their semi-final, which is where their loss was already recorded.
  if (m.round === "THIRD" || !m.winnerId) continue;
  const loserId = m.team1Id === m.winnerId ? m.team2Id : m.team1Id;
  if (loserId) knockoutLosers.add(loserId);
}

export function isEliminated(teamId: string): boolean {
  if (knockoutLosers.has(teamId)) return true;
  return groupStageComplete && !r32TeamIds.has(teamId);
}
