// Decimal outright-winner odds per team id, e.g. 5.5 (implied probability = 1/5.5).
// Generated by scripts/update-odds.ts from The Odds API. Do not hand-edit the
// GENERATED_ODDS object below — the next scheduled run overwrites it. For a one-off
// manual correction (e.g. the feed is late or wrong for one team), add an entry to
// ODDS_OVERRIDES instead.
const ODDS_OVERRIDES: Partial<Record<string, number>> = {
  // Keyed by team id, e.g. "ARG": 9.5.
};

// Seeded from a bookmaker board on 11 Jun 2026 (converted from the fractional prices
// this file used to store), kept up to date daily from there.
// --- GENERATED-BEGIN ---
const GENERATED_ODDS: Record<string, number> = {
  FRA: 6.0,
  ESP: 5.5,
  ARG: 10.0,
  ENG: 7.5,
  POR: 9.0,
  BRA: 9.0,
  NED: 21.0,
  MAR: 51.0,
  BEL: 34.0,
  GER: 15.0,
  CRO: 81.0,
  COL: 34.0,
  SEN: 126.0,
  MEX: 67.0,
  USA: 67.0,
  URU: 67.0,
  JPN: 51.0,
  SUI: 81.0,
  IRN: 501.0,
  AUT: 151.0,
  ECU: 101.0,
  KOR: 401.0,
  AUS: 501.0,
  EGY: 301.0,
  CAN: 126.0,
  CIV: 301.0,
  QAT: 2001.0,
  ALG: 401.0,
  SWE: 126.0,
  TUN: 501.0,
  CZE: 301.0,
  TUR: 81.0,
  NOR: 26.0,
  SCO: 251.0,
  COD: 751.0,
  BIH: 351.0,
  PAN: 1501.0,
  KSA: 1001.0,
  RSA: 1001.0,
  IRQ: 1501.0,
  UZB: 1501.0,
  PAR: 151.0,
  GHA: 401.0,
  JOR: 2501.0,
  CPV: 2001.0,
  CUW: 3501.0,
  HAI: 2501.0,
  NZL: 2501.0,
};
// --- GENERATED-END ---

export const ODDS_BY_ID: Record<string, number> = {
  ...GENERATED_ODDS,
  ...ODDS_OVERRIDES,
} as Record<string, number>;
