// Decimal outright-winner odds per team id, e.g. 5.5 (implied probability = 1/5.5).
// Generated by scripts/update-odds.ts from The Odds API. Do not hand-edit the
// GENERATED_ODDS object below — the next scheduled run overwrites it. For a one-off
// manual correction (e.g. the feed is late or wrong for one team), add an entry to
// ODDS_OVERRIDES instead.
const ODDS_OVERRIDES: Partial<Record<string, number>> = {
  // Keyed by team id, e.g. "ARG": 9.5.
};

// Seeded from a bookmaker board on 11 Jun 2026 (converted from the fractional prices
// this file used to store), kept up to date daily from there.
// --- GENERATED-BEGIN ---
const GENERATED_ODDS: Record<string, number> = {
  FRA: 2.99,
  ESP: 5.1,
  ARG: 5.05,
  ENG: 5.7,
  POR: 14.5,
  BRA: 13.5,
  NED: 21,
  MAR: 31.5,
  BEL: 36,
  GER: 15,
  CRO: 240.5,
  COL: 32.5,
  SEN: 145.5,
  MEX: 31.5,
  USA: 33.5,
  URU: 67,
  JPN: 51,
  SUI: 38,
  IRN: 501,
  AUT: 465.5,
  ECU: 101,
  KOR: 401,
  AUS: 475.5,
  EGY: 390.5,
  CAN: 335.5,
  CIV: 301,
  QAT: 2001,
  ALG: 655.5,
  SWE: 126,
  TUN: 501,
  CZE: 301,
  TUR: 81,
  NOR: 16.25,
  SCO: 251,
  COD: 305.5,
  BIH: 710.5,
  PAN: 1501,
  KSA: 1001,
  RSA: 1001,
  IRQ: 1501,
  UZB: 1501,
  PAR: 490.5,
  GHA: 535.5,
  JOR: 2501,
  CPV: 875.5,
  CUW: 3501,
  HAI: 2501,
  NZL: 2501,
};
// --- GENERATED-END ---

export const ODDS_BY_ID: Record<string, number> = {
  ...GENERATED_ODDS,
  ...ODDS_OVERRIDES,
} as Record<string, number>;
